"""Add requirements and tech_stack to project

Revision ID: 32c1a82e8bcc
Revises: 2f3c908a6593
Create Date: 2026-04-09 16:52:55.625295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '32c1a82e8bcc'
down_revision = '2f3c908a6593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('tech_stack', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'tech_stack')
    op.drop_column('project', 'requirements')
    # ### end Alembic commands ###
