"""
Models package for AI Programming System
"""
from sqlmodel import SQLModel

# 导入原有的用户和项目模型
from app.user_item_models import (
    User,
    UserCreate,
    UserUpdate,
    UserRegister,
    UserUpdateMe,
    UpdatePassword,
    UserPublic,
    UsersPublic,
    Item,
    ItemCreate,
    ItemUpdate,
    ItemPublic,
    ItemsPublic,
    Message,
    Token,
    TokenPayload,
    NewPassword,
)

# 导入AI编程系统的模型
from app.models.ai_programming import (
    Document,
    DocumentCreate,
    DocumentPublic,
    DocumentUpdate,
    DocumentsPublic,
    Error,
    ErrorCreate,
    ErrorPublic,
    ErrorUpdate,
    ErrorsPublic,
    ExecutionLog,
    ExecutionLogCreate,
    ExecutionLogPublic,
    ExecutionLogsPublic,
    FunctionModule,
    FunctionModuleCreate,
    FunctionModulePublic,
    FunctionModuleUpdate,
    FunctionModulesPublic,
    ProcessStage,
    ProcessStageCreate,
    ProcessStagePublic,
    ProcessStageUpdate,
    ProcessStagesPublic,
    Project,
    ProjectCreate,
    ProjectPublic,
    ProjectUpdate,
    ProjectsPublic,
    Session,
    SessionCreate,
    SessionPublic,
    SessionUpdate,
    SessionsPublic,
    SystemConfig,
    SystemConfigCreate,
    SystemConfigPublic,
    SystemConfigUpdate,
    SystemConfigsPublic,
    TestCase,
    TestCaseCreate,
    TestCasePublic,
    TestCaseUpdate,
    TestCasesPublic,
    TestReport,
    TestReportCreate,
    TestReportPublic,
    ToolConfig,
    ToolConfigCreate,
    ToolConfigPublic,
    ToolConfigUpdate,
    ToolConfigsPublic,
)

__all__ = [
    # User models
    "User",
    "UserCreate",
    "UserUpdate",
    "UserRegister",
    "UserUpdateMe",
    "UpdatePassword",
    "UserPublic",
    "UsersPublic",
    # Item models
    "Item",
    "ItemCreate",
    "ItemUpdate",
    "ItemPublic",
    "ItemsPublic",
    # Common models
    "Message",
    "Token",
    "TokenPayload",
    "NewPassword",
    # Project
    "Project",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectPublic",
    "ProjectsPublic",
    # ProcessStage
    "ProcessStage",
    "ProcessStageCreate",
    "ProcessStageUpdate",
    "ProcessStagePublic",
    "ProcessStagesPublic",
    # FunctionModule
    "FunctionModule",
    "FunctionModuleCreate",
    "FunctionModuleUpdate",
    "FunctionModulePublic",
    "FunctionModulesPublic",
    # TestCase
    "TestCase",
    "TestCaseCreate",
    "TestCaseUpdate",
    "TestCasePublic",
    "TestCasesPublic",
    # TestReport
    "TestReport",
    "TestReportCreate",
    "TestReportPublic",
    # ExecutionLog
    "ExecutionLog",
    "ExecutionLogCreate",
    "ExecutionLogPublic",
    "ExecutionLogsPublic",
    # Document
    "Document",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentPublic",
    "DocumentsPublic",
    # SystemConfig
    "SystemConfig",
    "SystemConfigCreate",
    "SystemConfigUpdate",
    "SystemConfigPublic",
    "SystemConfigsPublic",
    # ToolConfig
    "ToolConfig",
    "ToolConfigCreate",
    "ToolConfigUpdate",
    "ToolConfigPublic",
    "ToolConfigsPublic",
    # Session
    "Session",
    "SessionCreate",
    "SessionUpdate",
    "SessionPublic",
    "SessionsPublic",
    # Error
    "Error",
    "ErrorCreate",
    "ErrorUpdate",
    "ErrorPublic",
    "ErrorsPublic",
]
